//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuentiDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TuentiDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function() {
        ///  var el=document.createElement(&apos;div&apos;),
        ///   b=document.getElementsByTagName(&apos;body&apos;)[0];
        ///   otherlib=false,
        ///   msg=&apos;&apos;;
        ///  el.style.position=&apos;fixed&apos;;
        ///  el.style.height=&apos;32px&apos;;
        ///  el.style.width=&apos;220px&apos;;
        ///  el.style.marginLeft=&apos;-110px&apos;;
        ///  el.style.top=&apos;0&apos;;
        ///  el.style.left=&apos;50%&apos;;
        ///  el.style.padding=&apos;5px 10px&apos;;
        ///  el.style.zIndex = 1001;
        ///  el.style.fontSize=&apos;12px&apos;;
        ///  el.style.color=&apos;#222&apos;;
        ///  el.style.backgroundColor=&apos;#f99&apos;;
        ///  if(typeof jQuery!=&apos;undefined&apos;) {
        /// msg=&apos;This page already usin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jQueryLoader {
            get {
                return ResourceManager.GetString("jQueryLoader", resourceCulture);
            }
        }
    }
}
